# Generated by Django 5.0.1 on 2024-03-26 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0003_rename_comments_contactus_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
